name: Build APK with Buildozer

on:
  push:
    branches:
      - main  # Trigger when you push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use a Linux runner since Buildozer needs Linux

    steps:
      # Step 1: Checkout the code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python 3.x
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install necessary dependencies
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip git openjdk-8-jdk
          pip install buildozer[android]

      # Step 4: Run Buildozer to build the APK
      - name: Build APK
        run: |
          buildozer android debug

      # Step 5: Upload the generated APK
      - name: Upload APK as artifact
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: bin/*.apk
