name: Build APK with Buildozer

on:
  push:
    branches:
      - main  # Build the APK whenever you push to the main branch
  workflow_dispatch:  # Allow manual trigger from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from your repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python 3.x
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      # Step 3: Install dependencies (Python, Buildozer, Android SDK/NDK)
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip git openjdk-8-jdk wget unzip
          pip install --upgrade pip
          pip install buildozer

      # Step 4: Initialize Buildozer if the spec file is missing
      - name: Initialize Buildozer
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      # Step 5: Configure permissions and build the APK
      - name: Build APK
        run: |
          sed -i 's/# android.permissions =/android.permissions = INTERNET,WRITE_EXTERNAL_STORAGE,READ_EXTERNAL_STORAGE/' buildozer.spec
          buildozer -v android debug

      # Step 6: Upload the generated APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: bin/*.apk
